
netty:
  port: 8081
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mariadb://ff.codecraft.co.kr:33306/audition_hama_dev
      username: audition_dba
      password: 1q2w3e4r!!
      driver-class-name: org.mariadb.jdbc.Driver
      connection-test-query: SELECT 1
      connection-timeout: 60000
      maximum-pool-size: 10
      pool-name: primaryPool
    url: jdbc:mariadb://ff.codecraft.co.kr:33306/audition_hama_dev
mybatis:
  config-location: classpath:mapper/mapper-config.xml